#------------------------------------------------------------------------------

SOURCE=test.py 
MYPROGRAM=test
PY=python

#------------------------------------------------------------------------------



$(MYPROGRAM): $(SOURCE)

	$(PY)  $(SOURCE) children
	$(PY)  $(SOURCE) leftmost_child 


