#------------------------------------------------------------------------------

SOURCE=test.py 
OUTPUT=average_path.txt
MYPROGRAM=test
PY=python
LESS=less

#------------------------------------------------------------------------------



$(MYPROGRAM): $(SOURCE)

	$(PY)  $(SOURCE) 
	$(LESS)  $(OUTPUT)

